### ISSUE TITLE
MYSQL constants not existing anymore into Dialect

### ISSUE THREAD

**Issue by tleveque** [jklingsporn/vertx-jooq-async#7]
I got this error message
SEVERE: MYSQL_5_7
java.lang.NoSuchFieldError: MYSQL_5_7
	at io.github.jklingsporn.vertx.jooq.async.shared.internal.VertxDAOHelper.<clinit>(VertxDAOHelper.java:25)
	at io.github.jklingsporn.vertx.jooq.async.future.VertxDAO.findByIdAsync(VertxDAO.java:72)
	at com.turacoo.tyto.fo.ThemeVerticle.start(ThemeVerticle.java:35)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

I use following versions
<dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>3.9.2</version>
        </dependency>
        <dependency>
            <groupId>io.github.jklingsporn</groupId>
            <artifactId>vertx-jooq-async-future</artifactId>
            <version>0.4</version>
        </dependency>

It seems that Dialect constants have been removed and deprecated.
public class VertxDAOHelper {

    private VertxDAOHelper() {
    }

    static EnumSet<SQLDialect> INSERT_RETURNING_SUPPORT = EnumSet.of(SQLDialect.MYSQL,SQLDialect.MYSQL_5_7,SQLDialect.MYSQL_8_0);

**Comment by tleveque** [comment]
My mistake, I used jooq 3.9.2 instead of 3.10.1
It works now
