### ISSUE TITLE
Columns default value

### ISSUE THREAD

**Issue by quen2404** [jklingsporn/vertx-jooq-async#8]
Hi. thank you for your work, this jooq wrapper for vertx is pretty awesome !
In my database schema, i have some columns with default value like that:
`status        ENUM ('ACTIVE', 'SUSPENDED', 'DEACTIVATED') DEFAULT 'ACTIVE' NOT NULL,`
or that: 
`creation_date DATETIME DEFAULT CURRENT_TIMESTAMP                           NOT NULL,`
But when i'm trying to insert a row, an exception is raised saying that: 
```
com.github.mauricio.async.db.mysql.exceptions.MySQLException: Error 1048 - #23000 - Column 'status' cannot be null
	at com.github.mauricio.async.db.mysql.MySQLConnection.onError(MySQLConnection.scala:126) ~[mysql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.scala:107) ~[mysql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[netty-codec-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[netty-codec-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```
Is there a way to use columns default value or should i need to set a default value in my application code ?

**Comment by jklingsporn** [comment]
Hi @quen2404, thank you for your nice words.
I've recently released [vertx-jooq 3.0 (beta)](https://github.com/jklingsporn/vertx-jooq) which includes also an async wrapper. That means in turn that vertx-jooq-async will no longer be maintained. 
I'll add a test-case for the bug you mentioned to see if it is an issue there and see if I can fix it.

Best,
Jens

**Comment by quen2404** [comment]
Ok thank you. I will try the version 3.0-beta of vertx-jooq.
Just another little question. In the readme, it says that `The generator will omit datatypes that it does not know, e.g. java.sql.Timestamp`. Does the generator know by default a date type (like `java.time.LocalDateTime`) ?

**Comment by jklingsporn** [comment]
jOOQ does (if you set `<javaTimeTypes>true</javaTimeTypes>` in `<generate>`). The question is how you would put it into a `JsonObject`. If you overwrite `handleCustomTypeTo/FromJson` you can convert the `LocalDateTime` into a `String`. I [blogged](https://jensonjava.wordpress.com/2017/08/30/converting-a-jooq-record-into-a-vertx-jsonobject/) about the pros and cons some time ago.

**Comment by jklingsporn** [comment]
It turned out there was a flaw regarding default values in vertx-jooq 3.0.0-BETA. I've fixed those and released 3.0.0 just now. Regarding timestamp-conversion: checkout this [generator](https://github.com/jklingsporn/vertx-jooq/blob/master/vertx-jooq-generate/src/test/java/io/github/jklingsporn/vertx/jooq/generate/custom/CustomVertxGenerator.java) which converts the `LocalDateTime` into a `String` and vice versa in the [`from/toJson`](https://github.com/jklingsporn/vertx-jooq/blob/master/vertx-jooq-generate/src/test/java/generated/classic/jdbc/custom/vertx/tables/interfaces/ISomething.java)-methods.

**Comment by quen2404** [comment]
Hello.
Thank you for your help. Currently, i forked you project and we have the same generator. (I see that you changed `isType` method to protected, it's a good thing).
But i have another issue when i'm trying to use update method of one my DAO. I'm investigating this problem, so i will probably open you a new issue.

**Comment by jklingsporn** [comment]
Sure. But please consider doing it in vertx-jooq instead.
Thx,
Jens
